import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import NextAuthProvider from "@/providers/NextAuthProvider";


const inter = Inter({
  variable: "--font-inter-mono",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <NextAuthProvider session={session}>
      <html lang="en" className={inter.className}>
          <body className="min-h-screen w-auto">
            <Navbar />
            <div className="absolute mt-18 w-full">
                {children}
            </div>
          </body>
      </html>
    </NextAuthProvider>
  );
}
